### ISSUE TITLE
List on backdropcms.org

### ISSUE THREAD

**Issue by deekayen** [backdrop-contrib/token#12]
I see a release but the Token module isn't on the list at https://backdropcms.org/modules.

**Comment by klonos** [comment]
Token was initially ported and lived in contrib land, but was eventually [merged in core since 1.1](https://backdropcms.org/news/backdrop-1-1-released). There is a project node in backdropcms.org for it, but it is left unpublished so that users don't download and install it (it would conflict with the one in core).

I wanted to mention this to you so that you can remove the link to the lingering repository in github from [the README.md of session_limit](https://github.com/backdrop-contrib/session_limit/blob/1.x-1.x/README.md).
